### ISSUE TITLE
TCP read error: : Connection reset by peer

### ISSUE THREAD

**Issue by YuXinFan** [samee/obliv-c#100]
When I run my program with some `revealOblivBool(&e, oe, 2)` . I always receive `TCP read error: : Connection reset by peer`. I  don't know how to fix it. 

for example:
```c
obliv int * aa; obliv int * bb; obliv bool oeq; bool eq; void * temp=malloc(sizeof(obliv int));
...do something...
aa = (obliv int*)temp;
bb = (obliv int*)v;
oeq = *aa == *bb;
revealOblivBool(&eq, oeq, 2);
if (eq) { do something) else { do something)
...do something...
```
When I change `revealOblivBool(&eq, oeq, 2);` to `revealOblivBool(&eq, oeq, 0);`, it won't output error and execute successfully. But I actually want to reveal some information only to party 2.
I wonder why this problem occurs and how to fix it.

Thanks.

**Comment by weikengchen** [comment]
Usually, this happens when one party fails. You may want to debug in this direction. 

One possible direction: 
looks at 
`if (eq) { do something) else { do something)`

Is it possible that the two parties are running an entirely different program? That would have an issue because the garbler and the evaluator need to agree on the circuit to run.

**Comment by YuXinFan** [comment]
> Usually, this happens when one party fails. You may want to debug in this direction.
> 
> One possible direction:
> looks at
> `if (eq) { do something) else { do something)`
> 
> Is it possible that the two parties are running an entirely different program? That would have an issue because the garbler and the evaluator need to agree on the circuit to run.
Thanks for your reply.

From my understanding of Yao's protocol, the garbler doesn't need to do anything while the evaluator executes the circuit, except when they want to reveal some wires. So, the garbler doesn't need to know anything about the evaluator's execution. Is it right?

Do you mean: the garbler and evaluator simultaneously execute the circuit? or, the garbler and evaluator confirm the circuit?

I think you mean they confirm they generate or evaluate the same circuit.

My program structure is the same as the absentminded-crypto-kit project. I just execute the same program in two shells with different IP address parameters. It seems that they have no chance to execute two different programs.

I'm going to continue to look for the reason and how to fix it. 

If you have any ideas about it, please let me know.

**Comment by weikengchen** [comment]
In practice the implementation is often different from the textbook Yao’s protocol. In  obliv-c, the circuit description is never sent out and both parties need to agree on it, and the garbled circuit is sent gradually on the fly, pieces by pieces.

**Comment by YuXinFan** [comment]
------update------
fix some typo in the code snippet

------original comment------
I think I know why this problem occurs. 
I test a code snippet like this:
``` c
int eq_idx_k(obliv *data, int n, int k){
  int i = 0; 
  obliv int pi = data[k];
  for (int j = 0; j < n; j++) {
    oeq = pi == data[j];
    revealOblivBool(&eq, oeq, 2);
    if (eq) { 
      i = i + 1;
    }
  }  
  return i;
}
void eq_number(int *k, obliv *data, int n) {
  for (int i = 0; i < n; i++) {
      if (eq_idx_k(data, n, i) > n/2) {
          *k = i;
          return ;
      }
  }
}
```
The above code may be meanless. But I find that the garbler and evaluator execute the program simultaneously. When revealing `oeq` to party 2, party 2 may execute the `if` block in `eq_idx_k`, but party 1 never executes the `if` block because the default value of `eq` is false. Therefore, they execute in different control flows, and one finishes early so that the other one causes TCP error. 

If I really want to use the value of `eq` or `i` to control some following execution while revealing to only party 2(I think this way may be a security-performance trade-off ), how can I make it? In the above code snippet, how can I ensure the two parties execute with the same control flows?

**Comment by weikengchen** [comment]
It seems the hard part is to keep track of `data[i]`. It is like a conditional fetching from a queue. 

I think this is in general difficult. One way is to use an oblivious queue. If the dataset is small, use a linear scanning to fetch `data[i]` is also possible.
