### ISSUE TITLE
Failed to make Obliv-c

### ISSUE THREAD

**Issue by shivamag437** [samee/obliv-c#104]
I'm running Ubuntu 18.04.5 64-bit

I encounter the following error when trying to run make

`ocamlfind: matching/obliv-c/_build/src/ext/ccl/ccl.mli: No such file or directory`
`Makefile:389: recipe for target 'install-findlib' failed`
`make[1]: *** [install-findlib] Error 2`
`make[1]: Leaving directory '/home/shivam/Documents/stable matching/obliv-c`
`Makefile:413: recipe for target 'install-local' failed`
`make: *** [install-local] Error 2`

This does not seem to match the previous issues that have been raised with regards to installation.

I checked if `obliv-c/_build/src/ext/ccl/ccl.mli` exists on my local repository and it does

**Comment by weikengchen** [comment]
I have a guess---the space in the dir "stable matching" may have caused problems.

Please rename that directory and retry.

**Comment by shivamag437** [comment]
Oh thanks! I usually put underscores on folder names but forgot to do that here.
