### ISSUE TITLE
The cost of revealObliv()

### ISSUE THREAD

**Issue by YuXinFan** [samee/obliv-c#105]
Hi, I want to reveal some intermediate variables during the protocol execution. I make some tests of programs but find revealObliv() may have a high cost. Because both gate number and bytes number are reduced but time cost is increased.
What is the cost of revealObliv() function? Is it really high and why?

**Comment by samee** [comment]
How high a cost? And which protocol are you using (e.g. `execYaoProtocol()`?).

Generally speaking, `revealObliv()` is computationally one of the cheapest operation, but it can be slowed down by network latency. I.e. if your ping-time between machines is 5 ms, you might see something like 10 ms for a two-way reveal. This is in contrast to computing gates, which can be streamed and pipelined.

**Comment by YuXinFan** [comment]
> How high a cost? And which protocol are you using (e.g. `execYaoProtocol()`?).
> 
> Generally speaking, `revealObliv()` is computationally one of the cheapest operation, but it can be slowed down by network latency. I.e. if your ping-time between machines is 5 ms, you might see something like 10 ms for a two-way reveal. This is in contrast to computing gates, which can be streamed and pipelined.

Thanks, I use `execYaoProtocol()` as you said. Let me illustrate the problem I meet. 

Firstly, I run some tests programs on an i5-6300 pure Linux platform. All gate numbers, bytes numbers, and time costs are decreased (30%~50%). 
However, I rerun the same program on an i7-9700 WSL2 platform and on a Xeon Linux Server respectively. In the above two platforms, Gate numbers and byte numbers are decreased (30%~50%). But the time costs are increased (10%~100%). 
So I guess the problem may be caused by the `revealObliv()` function. But you say, `revealObliv()` is cheap, so I wonder why this happens.

**Comment by weikengchen** [comment]
This seems to be weird as if the program is the same, the gate count should not change a lot. Is the computation of the program deterministic? We need to check that first.

Note that the differences across the platforms may be explained by network latency or computation power.

**Comment by YuXinFan** [comment]
I will give more information. For example,
```C
void naive_psi1(obliv int *intersection, obliv int *aarr, obliv int *barr, int size){
    for (int i = 0; i < size; i++) {
        for (int j = 0; j < size; j++) {
            obliv if ( aarr[i] == barr[j]) {
                intersection[i] = barr[j];
            }
        }
    }
}

void naive_psi2(obliv int *intersection, obliv int *aarr, obliv int *barr, int size){
    for (int i = 0; i < size; i++) {
        for (int j = 0; j < size; j++) {
            obliv bool omatch = (aarr[i] == barr[j]);
            bool match;
            revealOblivBool(&match, omatch, 0);
            if ( match ) {
                intersection[i] = barr[j];
                break;
            }
        } 
    }
}
```
I get 
| | | |
| ---- | ---- | ----|
naive_psi1|Time/s| 0.26
naive_psi1|Gates/1e6| 0.63
naive_psi1|Bytes/MB| 20.16
naive_psi2|Time/s|0.18
naive_psi2|Gates/1e6| 0.15
naive_psi2|Bytes/MB| 5.02

on the i5-6300.

And get 
| | | |
| ---- | ---- | ---- |
naive_psi1|Time/s|0.160
naive_psi1|Gates/1e6|0.63
naive_psi1|Bytes/MB|20.16
naive_psi2|Time/s|0.34
naive_psi2|Gates/1e6|0.19
naive_psi2|Bytes/MB|6.22

on i7-9700.
Both of them run by cmd `naive_psi & naive_psi -c localhost` with 100 elements in aarr and barr and inputs are generated by
```C
aarr [i] = feedOblivInt(arrayA[i], 1);
barr[i] = feedOblivInt(arrayA[rand()%n], 2);
```
The time/gate/byte is the mean of 10 repetitions.

**Comment by samee** [comment]
Q: What does "bytes/MB" represent? Is it just the data transferred in MB?

In any case, I see that your naive_psi1 has the exact same number of bytes and gates in both machines. This is the behavior I'd expect to see, since the network protocol should not vary between CPU models or OS under any circumstance.

naive_psi2 uses far fewer gates than naive_psi1, as expected, since it is revealing more intermediate information. I can't really understand, though, if you ran them just once or multiple times. Do you still see this discrepancy between the two machines even if you run it say 10 times on each CPU model? Because naive_psi2 will vary in cost depending on input data. I can't really draw a lot of inference from just a single run.

**Comment by YuXinFan** [comment]
> Q: What does "bytes/MB" represent? Is it just the data transferred in MB?
> 
> In any case, I see that your naive_psi1 has the exact same number of bytes and gates in both machines. This is the behavior I'd expect to see, since the network protocol should not vary between CPU models or OS under any circumstance.
> 
> naive_psi2 uses far fewer gates than naive_psi1, as expected, since it is revealing more intermediate information. I can't really understand, though, if you ran them just once or multiple times. Do you still see this discrepancy between the two machines even if you run it say 10 times on each CPU model? Because naive_psi2 will vary in cost depending on input data. I can't really draw a lot of inference from just a single run.

A: Yes, "bytes/MB" is data transferred when communicating.

I agree that "naive_psi2 will vary in cost depending on input data". 
My main confusion is that both naive_psi2's gates and bytes are reduced, so time should decrease, but the fact is time increased.
And even though I make each repetition the same by 
```C
oarrA[i] = feedOblivInt(arrayA[i], 1); 
oarrB[i] = feedOblivInt(arrayA[n-1-i], 2);
```
The time of naive_psi2 is still larger than naive_psi1.
Follow is the cost in this case:
||||
|----|----|----|
naive_psi2| Time/s|0.34
naive_psi2|Gates/1e6|0.19
naive_psi2|Bytes/MB|6.22
