### ISSUE TITLE
Usage with Fedora

### ISSUE THREAD

**Issue by laumair** [samee/obliv-c#14]
Hey great library. I have been trying it out on ubuntu and have been trying to go through the examples and stuff. However, on Fedora I've been stuck with something pretty weird. So, I am trying to run `olinReg` tutorial by Samuel and it  gives me 

```
linReg.c:11:19: fatal error: obliv.h: No such file or directory
 #include <obliv.h>
                   ^
compilation terminated.
<builtin>: recipe for target 'linReg' failed
make: *** [linReg] Error 1
```

Please note that I have followed the exact same steps described in the README. And I have installed all the libraries and packages as dependencies listed in the doc. Is it something I am missing here?

**Comment by laumair** [comment]
Ah that was sort of stupid of me. I was trying to compile it with native compiler. We have to compile it with `oblivcc` as specified in docs in the bin directory. Closing this.

**Comment by samee** [comment]
Glad to know it's fixed now. For `.c` files you either can use `oblivcc` or can use `gc`c with `-I $OBLIVC_PATH/src/ext/oblivc`

**Comment by samee** [comment]
I meant `gcc`

**Comment by laumair** [comment]
@samee Thanks a lot 👍

**Comment by laumair** [comment]
@samee What about `.oc` files? So, lets say I have this really really basic piece of code that does nothing else but just declare a basic `obliv int`. And for simpilicity lets assume that files reside in the `bin` directory where we have the thin GCC wrapper `oblivcc`. Can you please specify how to:
1- Compile? Because I haven't had any luck with compiling `.oc` file with `obliv` declarations. 
2- Do I need any other header in that file other than `obliv.h`?

**Comment by samee** [comment]
Of I make a new file named test.oc, with just a single line `obliv int x;`, I can compile it with oblivcc -c test.oc. Obviously it cannot be linked without a proper main(), but it produces there object file. 

Seems like a lot of you are having related problems, all of which seems hard to reproduce on my end. What are you trying to write with Obliv-C? Are you just reproducing millionaire's problem, or is there some application you are targetting? Is this an assignment?

**Comment by laumair** [comment]
@samee Yeah I figured it out. Thanks though. This has been really helpful. 

So, to answer your second question. It is definitely not an assignment. I am targeting an application and I am currently just getting my hands dirty with the library because most probably I'd be using it for the application. So, at the moment I am just implementing few examples of my own and running the examples you have provided and its turning out great. 

The only resources I am following are https://eprint.iacr.org/2015/1153.pdf, https://docs.google.com/document/d/1n1hdBpRCr82wPYaG8is6nTtFdJ-RncoXCQZSyUqFP64/edit and of course the library itself. 

That being said, in the tutorial section currently there isn't any section provided for

```
feedOblivInputs, 
setupObliv,
revealObliv
ocBroadcastInt
```

Are they yet to be documented in the near future? Currently, I am targeting `feedOblivInputs` and `revealObliv`? Are there any resources I can take a look at for these two functions? Because, during implementation I am sort of confused on how to reveal the actual inputs. So, to be more elaborative lets say I am executing this: 

```
obliv bool f(obliv int x, int y) {
    return x>y;
}
```

How can we reveal the non-garbled boolean?

**Comment by samee** [comment]
Glad you figured it out. It might make sense for you to tell us what you
did to solve it, so that there next person has something to go on.

As for revealing values, you can reveal any output obliv bool to an
ordinary bool using revealOblivBool. It is used in the same way as
revealOblivInt, which you will see in the tutorial. Other resources include
test code you will find in test/oblivc.

And as always, you can ask here.

**Comment by laumair** [comment]
Yeah apologies. I think too it would be really nice if I'd keep sharing my experience throughout. 

So, lets say we have a `test.oc` file and it resides in the same `bin` folder where we have the compiler `oblivcc`. 

What I do is: 
- Make an object file using `./oblivcc -c test.oc` (Assuming we are currently inside the bin directory while we run this. After running this we will have an object code generated in the same directory we are in)
- Next I create an executable by `./oblivcc test.o -o test` that would create an executable file for us to run. 
- Simply: `./test`

**Comment by laumair** [comment]
Closing this now. I think this could be a reference for anybody who's starting with this great lib. I wouldn't want to post irrelevant issues here as it would collude with the issue title. Thanks @samee great help.

**Comment by samee** [comment]
Sounds good. In general, you wouldn't want to clutter all your source files in `bin/` folder. Instead, add `export PATH=$PATH:/path/to/bin` in your .bashrc so that `oblivcc` will work without explicit paths.

**Comment by laumair** [comment]
@samee :+1: Of course. Yeah I will do that. I am just consuming everything for exploration in the same file but yeah exporting path globally would definitely be a much cleaner and the right way.
