### ISSUE TITLE
Compilation error with obliv keyword in variable declaration

### ISSUE THREAD

**Issue by farhatnawaz** [samee/obliv-c#16]
Here is the a code snippet: 

```
 void millionaire (void *args) {
UserIO *io = args;
obliv int a, b;
obliv bool res = false;
a = feedOblivInt (io->myinput, 1);
 b = feedOblivInt (io->myinput, 2);
obliv if (a < b) res = true;
revealOblivBool (&io->result, res, 0);
}
```

When we try to compile this example, it generates an error with the obliv keyword. Every line of code where something is declared with an obliv keyword is generating an error.I have also attached a screenshot of the errors i am getting.

<img width="733" alt="screen shot 2016-10-27 at 9 17 56 pm" src="https://cloud.githubusercontent.com/assets/8686962/19775779/f5255026-9c8a-11e6-8760-b36c7034b2fb.png">  

We were first trying to write our own code but it was generating the same error. So we thought maybe something was wrong with our code. Then we took this example from http://www.ieee-security.org/TC/SP2015/posters/paper_62.pdf, but it end up with the same fate. please advise.

**Comment by laumair** [comment]
Got the same error. Any luck?

**Comment by samee** [comment]
Can you paste the exact command line you used? This is the error you would get if you are using gcc instead of oblivcc to compile. In particular, take a look at the readme here: https://github.com/samee/obliv-c/tree/obliv-c/test/oblivc

**Comment by farhatnawaz** [comment]
This is the command i used to compile the code `gcc -I /home/farhatnawaz/Downloads/oblivc/src/ext/oblivc basic.c`

**Comment by farhatnawaz** [comment]
I just ran the example specified in the link you mentioned earlier`gcc -I /home/farhatnawaz/Downloads/oblivc/src/ext/oblivc editdist.c`. I used this command and it throws the following error

```
/tmp/ccbPEALc.o: In function `main':
editdist.c:(.text+0x179): undefined reference to `ocTestUtilTcpOrDie'
editdist.c:(.text+0x1b4): undefined reference to `setCurrentParty'
editdist.c:(.text+0x1be): undefined reference to `wallClock'
editdist.c:(.text+0x1d7): undefined reference to `editDistance'
editdist.c:(.text+0x1df): undefined reference to `execYaoProtocol'
editdist.c:(.text+0x1e9): undefined reference to `wallClock'
editdist.c:(.text+0x234): undefined reference to `yaoGateCount'
editdist.c:(.text+0x25b): undefined reference to `cleanupProtocol'
collect2: error: ld returned 1 exit status
```

**Comment by farhatnawaz** [comment]
We have also tried to compile the million example using the oblivcc compiler with the command `make CC="./oblivcc" ./million/million million.oc`. But it also generates some error which is as follows

```
./oblivcc     million/million.c   -o million/million
/usr/bin/ld: cannot find -lobliv
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'million/million' failed
make: *** [million/million] Error 1
```

**Comment by samee** [comment]
Please try the exact commands in the readme first.

**Comment by farhatnawaz** [comment]
```
/home/farhatnawaz/Downloads/oblivc/bin/oblivcc -I
/usr/bin/ld: cannot find /home/farhatnawaz/Downloads/oblivc/src/ext/oblivc: File format not recognized
/usr/bin/ld: cannot find -lobliv
collect2: error: ld returned 1 exit status

```

This is what i am getting with the exact command in README

**Comment by samee** [comment]
I am having trouble following you and reproducing your problems. Can you please paste the command you invoked, and the current directory you are in when you are in when you see these error messages? Also, have you started by building Obliv-C with `./configure && make RELEASE=1`? That's necessary for any of this to work. (readme [here](https://github.com/samee/obliv-c))

**Comment by farhatnawaz** [comment]
Okay sorry I will be more elaborative about the problem here. 

So, after cloning the repo on `Ubuntu` system, I installed all the dependencies by: 

`sudo apt-get install ocaml libgcrypt20-dev ocaml-findlib`

After the installation of all dependencies, I did `./configure && make RELEASE=1` after cd into the cloned directory of the library which would be: `farhatnawaz@ubuntu:~/Downloads/samee-obliv$` 

So, it successfully configures the library. The issue comes after that. So, I have this small piece of code with `obliv` keywords/variables and on compilation it throws error on every `obliv` keyword. 

_Directory  the code resides is: _farhatnawaz@ubuntu:~/Documents_

**basic.c** is the program that I want to compile with oblivc. 

**Code** 

```
#include <stdio.h>
#include <obliv.h>

typedef struct { int myinput; bool result; } UserIO;

 void millionaire (void *args) {
UserIO *io = args;
obliv int a, b;
obliv bool res = false;
a = feedOblivInt (io->myinput, 1);
 b = feedOblivInt (io->myinput, 2);
obliv if (a < b) res = true;
revealOblivBool (&io->result, res, 0);
}

 int main (int argc, char *argv[]) {
ProtocolDesc pd;
UserIO io;

setCurrentParty (&pd, (argv[1] == "1" ? 1 : 2));
 sscanf(argv[2], "%d", &io.myinput);
execYaoProtocol (&pd, millionaire, &io);
printf ("Result: %d\n", result);
 }

```

For compilation I am in the same directory as the `basic.c` is and I am running:

`gcc -I /home/farhatnawaz/Downloads/samee-obliv/src/ext/oblivc basic.c`
_This should be noted that the file I am trying to execute is in the `Documents` dir while I have `oblivc` inside `Downloads`. I don't think that would cause any issue because I am linking it with the library at compile time._ 

So after I run that, I get errors on every `obliv` keyword. I am attaching a screenshot below of all the errors that I get. 

**NOTE** This error prevails on every single program I wrote and try to compile it with oblivc. 
I am kind of really stuck with this and have found no luck whatsoever on my end. I would really appreciate if you could point me in the right direction for this. Thanks. 

Below is the screenshot of the errors. 

![screenshot from 2016-10-27 22-54-09](https://cloud.githubusercontent.com/assets/8686962/19796323/5d6c169e-9c98-11e6-8e68-14331d35a2c8.png)

**Comment by samee** [comment]
Thanks for the details. I see that you are using gcc here, which is the built-in C compiler. It does not know about Obliv-C keywords (such as obliv ~~Obliv-C~~). In order to enable proper compilation, please use oblivcc, and rename your file to a .oc extension. Here is what oblivcc does:
- If you provide it with an .oc file, it will be compiled as an Obliv-C program.
- If you provide a .c file, it is assumed to be a C file, and is passed into gcc without any further processing.

You might also need to #include a few more files.

(edited later for formatting and typos)

**Comment by farhatnawaz** [comment]
Thankyou so much. This really helped. I was able to resolve the issue.
