### ISSUE TITLE
Modifying sourcecode of Obliv C to fit requirements

### ISSUE THREAD

**Issue by guruvamsi-policharla** [samee/obliv-c#21]
I'm trying to modify the yaoKeyNewPair in order to use my own method to generate the keys and read them from a file. For this, I'm guessing I have to do "./configure && make RELEASE=1" every time I modify a part. However, I'm unable to redo this after making changes a second time as it runs into an error during compilation. This becomes tedious for testing. Looking for suggestions.
Thanks!

**Comment by samee** [comment]
Usually you don't have to run configure. Only make RELEASE=1
