### ISSUE TITLE
total communication size

### ISSUE THREAD

**Issue by haochenuw** [samee/obliv-c#23]
...not really an issue, but it'd be very helpful if we can see the total communication size within an execution. Could you give some instructions? Thanks!

**Comment by jackdoerner** [comment]
In the current obliv-c source, you can uncomment the #define PROFILE_NETWORK on line 59 of obliv_bits.c, then use tcp2PBytesSent() and tcp2PFlushCount() to retrieve the bytes sent and number of explicit flushes done (which is roughly equivalent to the number of rounds, if I understand correctly). In an upcoming version, you'll be able to use these functions without recompiling obliv-c. There's a PR from me for this currently, but it needs a reorganization before it gets merged. Hopefully sometime before the end of April.

**Comment by haochenuw** [comment]
That was very helpful. Thank you very much!

**Comment by haochenuw** [comment]
When I try to use tcp2PBytesSent(), I got 

> TCP read error:  No such file or directory

Could you let me know where I messed up? To reproduce the error, I added the following two lines to 
test/oblivc/editdist/editdist.c

```
size_t comm = tcp2PBytesSent(&pd);
printf("total communication : %s \n", comm); 
```

**Comment by haochenuw** [comment]
Never mind, I should have used %zu. Thank you!

**Comment by zxf8876983** [comment]
Why is the result returned by the tcp2PBytesSent() zero?
