### ISSUE TITLE
How to Compile Code using GCC Wraper 

### ISSUE THREAD

**Issue by suhelsayyad2006** [samee/obliv-c#31]
Hello

I am bit newbie to this system. Please help me understand how to I compile sample million.c

I am unable to understand how to give path and all. Please help

**Comment by jackdoerner** [comment]
I assume that you have a copy of obliv-c and that it's been compiled, and also that you're reasonably familiar with command line interaction. If the former is not true, see the README; if the latter is not true, you should probably spend some time becoming comfortable with bash. Google will help you in that case. Regardless, if you have those two prerequisites, then you have the obliv-c project somewhere (for example, it might be `~/obliv-c` if it's in your home directory). From within the `test/oblivc/million` subdirectory, you need to call `../../../bin/oblivcc million.c million.oc -I .` to produce a binary.
In general, the `oblivcc` command should work just like `gcc`, so many questions about options and flags can be answered by reading `gcc`'s documentation.

**Comment by suhelsayyad2006** [comment]
I am not able to compile the code. I installed the library as per the instructions. But unable to understand meaning of 

# compile using our GCC wrapper
/path/to/oblivcc million.c million.oc -I

**Comment by samee** [comment]
It seems this thread has been a bit neglected, sorry. You will find a script called `oblivcc` in `bin/`. The readme was asking you to run that. Feel free to go through the tutorial at http://oblivc.org/ as well, and email me if problem persists.

Marking this thread as closed for now.
