### ISSUE TITLE
failed to run:/obliv-c/test/oblivc/million

### ISSUE THREAD

**Issue by zxf8876983** [samee/obliv-c#46]
~/obliv-c/test/oblivc/million$ ./a.out 1 15 | ./a.out 2 10
�c��4��N�So��M�p/�4�L����ㇰu7�1ûOu�Ē��Z}�H�h�������ρ�dC�>�֢�uP�j���\�
���Ş�k��T*k��-�lo�h��G>a��XL
(-"'_`�c	�F>�h�dqm�'�	�~��K�>w������K�%|�!���z�����k
                                                                 ��
�������U�t��ߎ���4֖��s~�/�?5��U��;X�_(�m��ڣԔ�>ԟX�v�צ���g"�:ٛO��&�a�bެ�	�r������SvH��gޏ0^79��u!�B�u���;�
                           Y�"��녞��R��΁�ѳlؽ�q6���l@8�WW�xlb�?F�J�%9ˊ����OtD��
   v~���t�Jh��&�Aإ�V�<(M��b*�a�K�
@���~��t@EH�L��h�g��L�����0�χ�:
�b;��(p"���d�s�b|��9����!���a8�>8?���-f���쮣��nJ9zE���r��
                                                                  ����9l�n�
                                                                            r��'�\��}S�$��pT�!{?<k�?�l�w�������RV�ʂTT)��q0��C�xG��%�{�t�%q{՛
                                                                 ��VqjE�#O�W`���F��UA]E�
      /a%�m������S�п
......
......
......

**Comment by samee** [comment]
Please use the cycle command as described in here: https://github.com/samee/obliv-c/blob/obliv-c/test/oblivc/million/README.txt
