### ISSUE TITLE
Obliv-C fails to build on newer OCaml versions

### ISSUE THREAD

**Issue by samee** [samee/obliv-c#49]
The whole world caught fire after I updated `ocamlbuild` on my machine. Unfortunately, I did not keep a detailed log of everything I did to fix this, but it essentially involved switching to OPAM:

```
sudo apt install opam m4
opam init
opam switch 4.06.0
eval `opam config env`
opam install camlp4 ocamlfind ocamlbuild
```

After this, I had to spend a fair bit of time debugging a few String deprecation issues. There are still some warnings left, but at least it builds on my machine. Need to test more before I push this in.

Interestingly, issue #44 became a problem on my machine as well. I'll upload the fix in a new branch.

**Comment by samee** [comment]
Pushed out [ocaml-update](https://github.com/samee/obliv-c/tree/ocaml-update) branch. Need to test.

**Comment by samee** [comment]
Since I don't remember exactly what I did, and don't have tmux logs, we'll need to try out these steps before changing the repository README.md.

**Comment by edoroth** [comment]
I'm also unable to make Obliv-C. I get the following:

ocamlfind: Work/obliv-c/_build/src/ext/zrapp/reachingdefs.inferred.mli: No such file or directory.

As a result, can't run any of the files because it hasn't been properly built, and some build files are missing.

Tried your suggested fix but wasn't able to change anything. Any suggestions?

**Comment by samee** [comment]
Can you post a complete log from a clean directory? It seems like there was some earlier error that caused the "reachingdefs" file not to get built.

**Comment by edoroth** [comment]
Ah, when I re-clone and try installing, I now get the following:

File "myocamlbuild.ml", line 1:
Error: /usr/local/Cellar/ocamlbuild/0.12.0/lib/ocamlbuild/ocamlbuild_plugin.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.
Command exited with code 2.
make[1]: *** [ocamlbuild] Error 10
make: *** [install-local] Error 2


I'm on OCaml 4.05.0.

**Comment by samee** [comment]
Ok, and I'm on OCaml 4.06. Try the opam steps in the top comment now.

**Comment by schoppmp** [comment]
When building with OCaml 4.06, I also have compilation problems: [error.txt](https://github.com/samee/obliv-c/files/1689547/error.txt).
As far as I can see, the main problem lies here, but probably that's not the end of the story:
```
File "src/cilint.mli", line 6, characters 36-51:
Error: Unbound module Big_int
```
This happens on both branches, master and ocaml-update, and whether I install ocaml via pacman or opam.
Any ideas?

**Comment by samee** [comment]
Try installing batteries: http://batteries.forge.ocamlcore.org/doc.preview:batteries-beta1/html/api/Big_int.html

`opam install batteries`

**Comment by schoppmp** [comment]
Thanks, that worked.

**Comment by samee** [comment]
Merged in ocaml-update branch. Closing this issue for now, feel free to reopen if problem persists.
