### ISSUE TITLE
failed to install Obliv-C

### ISSUE THREAD

**Issue by chennyc** [samee/obliv-c#51]
Hi! there, I was trying to install Obliv-C in my machine(Ubantu) by following the instructions of "Installation" section. After ./configure, I tried to do the `make`, and then the following errors happened:
`chen@chen:~/Documents/obliv-c-obliv-c$ make
make cilly install-findlib install-data PREFIX=. datarootdir=share DESTDIR= OCAMLFIND_DESTDIR=lib
make[1]: Entering directory `/home/chen/Documents/obliv-c-obliv-c'
export CIL_VERSION
MAKE=make ocamlbuild -build-dir _build -use-ocamlfind -no-links -classic-display src/cil.cma src/ext/blockinggraph.cma src/ext/callgraph.cma src/ext/canonicalize.cma src/ext/ccl.cma src/ext/cqualann.cma src/ext/dataslicing.cma src/ext/epicenter.cma src/ext/heapify.cma src/ext/inliner.cma src/ext/liveness.cma src/ext/llvm.cma src/ext/logcalls.cma src/ext/logwrites.cma src/ext/oneret.cma src/ext/partial.cma src/ext/processObliv.cma src/ext/pta.cma src/ext/sfi.cma src/ext/simplemem.cma src/ext/simplify.cma src/ext/zrapp.cma src/cil.libfiles src/ext/blockinggraph.libfiles src/ext/callgraph.libfiles src/ext/canonicalize.libfiles src/ext/ccl.libfiles src/ext/cqualann.libfiles src/ext/dataslicing.libfiles src/ext/epicenter.libfiles src/ext/heapify.libfiles src/ext/inliner.libfiles src/ext/liveness.libfiles src/ext/llvm.libfiles src/ext/logcalls.libfiles src/ext/logwrites.libfiles src/ext/oneret.libfiles src/ext/partial.libfiles src/ext/processObliv.libfiles src/ext/pta.libfiles src/ext/sfi.libfiles src/ext/simplemem.libfiles src/ext/simplify.libfiles src/ext/zrapp.libfiles src/main.byte cil.docdir/index.html
ocamlfind ocamlc -c -I src -I src/ocamlutil -I src/frontc -I src/ext -I src/ext/pta -I src/ext/inliner -I src/ext/sfi -I src/ext/ccl -I src/ext/blockinggraph -I src/ext/partial -I src/ext/heapify -I src/ext/llvm -I src/ext/simplify -I src/ext/epicenter -I src/ext/logwrites -I src/ext/callgraph -I src/ext/canonicalize -I src/ext/dataslicing -I src/ext/oneret -I src/ext/oblivc -I src/ext/liveness -I src/ext/simplemem -I src/ext/zrapp -I src/ext/cqualann -I src/ext/logcalls -I src/ext/processObliv -o src/cilint.cmi src/cilint.mli
+ ocamlfind ocamlc -c -I src -I src/ocamlutil -I src/frontc -I src/ext -I src/ext/pta -I src/ext/inliner -I src/ext/sfi -I src/ext/ccl -I src/ext/blockinggraph -I src/ext/partial -I src/ext/heapify -I src/ext/llvm -I src/ext/simplify -I src/ext/epicenter -I src/ext/logwrites -I src/ext/callgraph -I src/ext/canonicalize -I src/ext/dataslicing -I src/ext/oneret -I src/ext/oblivc -I src/ext/liveness -I src/ext/simplemem -I src/ext/zrapp -I src/ext/cqualann -I src/ext/logcalls -I src/ext/processObliv -o src/cilint.cmi src/cilint.mli
File "src/cilint.mli", line 6, characters 36-51:
Error: Unbound module Big_int
Command exited with code 2.
make[1]: *** [ocamlbuild] Error 10
make[1]: Leaving directory `/home/chen/Documents/obliv-c-obliv-c'
make: *** [install-local] Error 2`

By the way, I have already installed the Ocaml compiler, Ocamlbuild, and Ocaml findlib, which are required during configure. Please any idea where this error comes from?

**Comment by samee** [comment]
It's probably because I should update the README by now. Read through https://github.com/samee/obliv-c/issues/49, and see if the symptoms and solutions work for you.

**Comment by chennyc** [comment]
Thanks for your advice. The error message, in this case, was identical to the #49 's. 
After I tried the commands in the top of #49 and also installed batteries, however, it still didn't work and the error message changed into this:

...
File "src/formatlex.mll", line 150, characters 4-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "src/formatlex.mll", line 150, characters 4-8:
Error: This expression has type string but an expression was expected of type
         bytes
Command exited with code 2.
make[1]: *** [ocamlbuild] Error 10
make[1]: Leaving directory `/home/chen/Documents/obliv-c-obliv-c'
make: *** [install-local] Error 2

**Comment by chennyc** [comment]
I've reinstalled the OS on my machine and configured the obliv c from the beginning. I don't know why but it finally works now. Thanks for your suggestions and efforts all the same.

**Comment by samee** [comment]
Sorry for the trouble. Usually just cloning to a fresh repository solves the OCaml issues. I hope you won't have to reinstall your OS every time there's a problem.
