### ISSUE TITLE
Incorrect subtraction result in testFloatOps.c 

### ISSUE THREAD

**Issue by ntrolls** [samee/obliv-c#54]
The test result for subtraction in `testFloatOps.c` seems incorrect. Below is what I get from the current build. I tested under Ubuntu 14.04 and OS X 10.13.3. 

```
Addition: 3.579000
01101010011100001010011000000010

Subtraction: 1.111000
00000010101011000111000111111100

Multiplication: 2.893730
11111011010011001001110000000010

Division: 0.526226
11111101011011010110000011111100

Negation: -1.234000
01101101110011111011100111111101
```

The subtraction is supposed to compute 1.234 - 2.345, so the result should be negative. In fact, the current result is different only by the sign. Am I missing something? Or is there a problem with the handling of the sign bit in `float`?

**Comment by samee** [comment]
@darioncassel, can you take a look at this? I have not had a chance to rerun this test yet.

**Comment by darioncassel** [comment]
From the looks of it 2.345 - 1.234 is being computed instead of 1.234 - 2.345; while the result is not wrong, it seems the subtraction operands might be switched. I will look into this tomorrow to check whether the error is with the test file or something else.

**Comment by ntrolls** [comment]
I wrote an `int` version of `testFloatOps` and the subtraction for integers work correctly. While I have zilch working knowledge of Ocaml, I skimmed through the CIL part of the framework and I think operands are handled in the same order for both `int` and `float` by CIL. The only difference is that, while the integer subtraction is implemented by `void __obliv_c__setBitsSub (void* vdest, void* borrowOut                           ,const void* vop1,const void* vop2,const void* borrowIn,size_t size)`, the float subtraction is in `void obliv_float_sub_circuit(OblivBit* dest, const OblivBit* op1, const OblivBit* op2)` in `oblivion_float_sub.c`.

So I suspect whether the likely explanation is that the float subtraction function expects a different operand order. In fact, the following patch results in correct subtraction test for both `int` and `float`.

```
diff --git a/src/ext/oblivc/obliv_bits.c b/src/ext/oblivc/obliv_bits.c
index cd5ac7c0..4b8462fa 100644
--- a/src/ext/oblivc/obliv_bits.c
+++ b/src/ext/oblivc/obliv_bits.c
@@ -1707,7 +1707,7 @@ void __obliv_c__setPlainSubF (void* vdest
                              ,size_t size)
 { OblivBit *dest=vdest;
   const OblivBit *op1=vop1, *op2=vop2;
-  obliv_float_sub_circuit(dest, op1, op2);
+  obliv_float_sub_circuit(dest, op2, op1);
 }
 
 #define MAX_BITS (8*sizeof(widest_t))
```

A confirmation from someone who knows the full depth of oblivc would be nice :)

**Comment by darioncassel** [comment]
@ntrolls Thanks for your comments! You're right that the error isn't with the Obliv-C parser or code generator; I've confirmed that a direct call to the ```__obliv_c__setPlainSubF``` function still results in the apparently switched operand order.

However, after some digging I've found that the issue lies a bit deeper. It seems that there's a problem in the floating point subtraction circuit. For context, the subtraction circuit is the same as the addition circuit but the difference is that a sign bit is switched for one of the operands. I made a mistake when generating this circuit and switched the sign of the first operand rather than the second. Therefore, this change should fix it:
```
diff --git a/src/ext/oblivc/obliv_float_sub.c b/src/ext/oblivc/obliv_float_sub.c
old mode 100644
new mode 100755
index 408bc49b..b208fd7a
--- a/src/ext/oblivc/obliv_float_sub.c
+++ b/src/ext/oblivc/obliv_float_sub.c
@@ -2067,7 +2067,6 @@ void obliv_float_sub_circuit(OblivBit* dest, const OblivBit* op1, const OblivBit
     __obliv_c__copyBit(&__obliv_29, op1+29);
     __obliv_c__copyBit(&__obliv_30, op1+30);
     __obliv_c__copyBit(&__obliv_31, op1+31);
-    __obliv_c__flipBit(&__obliv_31);
     __obliv_c__copyBit(&__obliv_32, op2+0);
     __obliv_c__copyBit(&__obliv_33, op2+1);
     __obliv_c__copyBit(&__obliv_34, op2+2);
@@ -2100,6 +2099,7 @@ void obliv_float_sub_circuit(OblivBit* dest, const OblivBit* op1, const OblivBit
     __obliv_c__copyBit(&__obliv_61, op2+29);
     __obliv_c__copyBit(&__obliv_62, op2+30);
     __obliv_c__copyBit(&__obliv_63, op2+31);
+    __obliv_c__flipBit(&__obliv_63);
     __obliv_c__setBitNot(&__obliv_64, &__obliv_30);
     __obliv_c__setBitAnd(&__obliv_65, &__obliv_62, &__obliv_64);
     __obliv_c__setBitNot(&__obliv_65, &__obliv_65);
```

@samee Would you like me to submit this as a PR?

**Comment by samee** [comment]
Sure, a PR sounds good.

It sounds like either patch will solve the issue then?

**Comment by darioncassel** [comment]
Ok, I’ll submit a PR. 

Both patches will solve the issue but I recommend fixing it at the level of the float subtraction circuit because that’s the root of the problem.

Edit: PR has been submitted.

**Comment by ntrolls** [comment]
Thanks! Expect another publication that depends on obliv-c soon :)
