### ISSUE TITLE
Build problem when using Homebrew in OS X

### ISSUE THREAD

**Issue by ntrolls** [samee/obliv-c#55]
There is a subtle (okay, subtle to those who are not very familiar with Perl) issue when trying to build Obliv-C using Homebrew in OS X. Homebrew installs gcc 5.x at `/usr/local/Cellar/gcc@5/....`. When this is fed into `configure` and `make`, the `@` fails to escape in `lib/perl5/App/Cilly.pm`. This can result in the same symptom as the one pointed out in #44 even when `-dumpversion` is correctly returning the full version.

I found that symlinking `gcc@5` to something like `gcc-5` and using this as a workaround, but it would be nice if the `@` is supported seamlessly.

**Comment by samee** [comment]
Thanks, I'll be the first to admit that I never tried being a Perl-master. Why don't you patch this up here, and maybe @jackdoerner can test it out? I don't really have a Mac handy, so I can't test this myself.

**Comment by ntrolls** [comment]
I will investigate once I get some time.

**Comment by ntrolls** [comment]
Okay, it was a (silly) mistake on my part. I am not supposed to use the path with `@5` - there is a perfectly working symlink, created by `homebrew`, in the form of `/usr/local/bin/gcc-5`. In fact, I just upgrade to `gcc-7` provided by `homebrew` and successfully built obliv-c without patching anything. So please ignore this issue.
