### ISSUE TITLE
Problem on `cilly` with `goto` in <gmp.h>

### ISSUE THREAD

**Issue by weikengchen** [samee/obliv-c#58]
The problem is in `cilobliv`.

When I include <gmp.h> in a `.oc` program, `cilly` will first generate `xxx.cil.c`.

Below is the code in <gmp.h>
```
#define __GMPN_AORS(cout, wp, xp, xsize, yp, ysize, FUNCTION, TEST)     \
  do {                                                                  \
    mp_size_t  __gmp_i;                                                 \
    mp_limb_t  __gmp_x;                                                 \
                                                                        \
    /* ASSERT ((ysize) >= 0); */                                        \
    /* ASSERT ((xsize) >= (ysize)); */                                  \
    /* ASSERT (MPN_SAME_OR_SEPARATE2_P (wp, xsize, xp, xsize)); */      \
    /* ASSERT (MPN_SAME_OR_SEPARATE2_P (wp, xsize, yp, ysize)); */      \
                                                                        \
    __gmp_i = (ysize);                                                  \
    if (__gmp_i != 0)                                                   \
      {                                                                 \
        if (FUNCTION (wp, xp, yp, __gmp_i))                             \
          {                                                             \
            do                                                          \
              {                                                         \
                if (__gmp_i >= (xsize))                                 \
                  {                                                     \
                    (cout) = 1;                                         \
                    goto __gmp_done;                                    \
                  }                                                     \
                __gmp_x = (xp)[__gmp_i];                                \
              }                                                         \
            while (TEST);                                               \
          }                                                             \
      }                                                                 \
    if ((wp) != (xp))                                                   \
      __GMPN_COPY_REST (wp, xp, xsize, __gmp_i);                        \
    (cout) = 0;                                                         \
  __gmp_done:                                                           \
    ;                                                                   \
  } while (0)
```

Note that it uses `__gmp_done`, and the `__gmp_done` is in at the end of the `do` bracket.

However, `cilobliv` removes the label, but still uses that `goto`, causing the label missing. Take a look at `xxx.cil.c`.

```
#line 2135  
            __gmp_c = (mp_limb_t )1;
#line 2135  
            goto __gmp_done;
          }
          }
#line 2135
          __cil_tmp19 = __gmp_xp + __gmp_i;
```

Where the label `__gmp_done` should have appeared somewhere after `__gmp_c = (mp_limb_t )0;` below, but not.

```
#line 2135
    __gmp_c = (mp_limb_t )0;

#line 2135
    break;
  }
#line 2136
  return (__gmp_c);
}
}
```

To try to circumvent this issue, I include <gmp.h> in `.c`, not `.oc`, but it does not work, because:
     `oblivcc` never calls `cilobliv` directly, but uses `cilly`. Therefore, even `.c` files are also preprocessed with `cilly`.

I change the code in `oblivcc`, which only preprocess `.oc` with `cilobliv`:
https://gist.github.com/weikengchen/0185d72f29f746cabfb2222b40b0a4a3
which circumvents the issue.

Question: Why `obliv-c` made the decision to process all files using `cilly`?

**Comment by weikengchen** [comment]
and formally, any idea on fixing `cilly` against such goto labels?

Is that an easy-to-fix problem?

**Comment by samee** [comment]
Hey, thanks for all the debugging. The short answer is that it is better to use gcc/clang for plain C files, and link them in separately.

```shell
gcc foo.c -c -o foo.c.o
$OBLIVC_PATH/bin/oblivcc foo.oc -c -o foo.oc.o
$OBLIVC_PATH/bin/oblivcc foo.c.o foo.oc.o -o foo
```

The last line links all previous `.o` files into an executable binary `foo`. You will find some (probably hard-to-read) examples in [sqrtOram Makefile](https://github.com/samee/sqrtOram/blob/master/Makefile), where you will see `.c` and `.oc` files being processed by different Makefile rules.

As for the rationale, it was because the `obliv`-related type rules are hard to design for `goto`, so we decided not to support it at all. We should probably just raise an error instead of silently generating the wrong code though. We also didn't want to fix it in `oblivcc`, since we didn't want to force a file naming convention for users, so they can name their Obliv-C files `.c` if they wanted to (in hindsight, we probably don't need to allow that). Without actually testing it, I'll say that I *think* the original `cilly` handles `goto` reasonably well, at least without any of our Obliv-C modifications.

Hope this helps.

**Comment by weikengchen** [comment]
Thanks. 
sqrtOram's Makefile is a good template.

**Comment by weikengchen** [comment]
I guess what you mentioned is:
https://github.com/samee/obliv-c/blob/obliv-c/src/ext/processObliv/processObliv.ml

```
  method vstmt s = let restore = self#getRestorer() in begin
    match s.skind with
    | If(c,tb,fb,loc) -> if isOblivBlock tb then
          (breakOk:=false; contOk:=false; returnOk:=false)
    | Loop _ -> breakOk:=true; contOk:=true
    | Switch _ -> breakOk:=true
    | TryFinally _ | TryExcept _ -> 
        E.s (E.error "%a: Obliv-C does not support exceptions"
          d_loc !currentLoc)
    | Break loc -> if not !breakOk then
                      E.s (E.error "%a: unexpected break" d_loc loc)
    | Continue loc -> if not !contOk then
                        E.s (E.error "%a: unexpected continue" d_loc loc)
    | Return (_,loc) -> if not !returnOk then
                          E.s (E.error "%a: unexpected return" d_loc loc)
    | _ -> (); (* Yeah, I'm not handling Goto *)
    ;
    ChangeDoChildrenPost(s,fun s -> restore(); s)
end
```

Where it seems you simply drop all the rest :)
(I start to forget my compiler theory course but it looks like...)
