### ISSUE TITLE
Please tell me why the result returned by the function is zero?

### ISSUE THREAD

**Issue by zxf8876983** [samee/obliv-c#60]
In the .c file:
size_t comm = tcp2PBytesSent(&pd);
printf("total communication : %zu \n", comm);

**Comment by cwk32** [comment]
src/ext/oblivc/obliv_bits.c
is relevant.

Please check whether the TCP link you used was set to be profiled.

**Comment by zxf8876983** [comment]
Should I replace protocolAcceptTcp2P() with protocolAcceptTcp2PProfiled?
thanks for your help.

**Comment by weikengchen** [comment]
I feel that should work. Please have a try and close this issue if it works.

Basically, you need to modify line 81 in https://github.com/zxf8876983/MyTest/blob/master/1-nn/nn.c
Note: you'd better also test whether profiled version added significant end-to-end inference latency compared with the non-profiled version.

**Comment by weikengchen** [comment]
Just for curiosity, are you Xianfeng Zhao in IIE?

**Comment by zxf8876983** [comment]
@weikengchen Sorry, I'm not Xiangfeng Zhao

**Comment by zxf8876983** [comment]
@cwk32 @weikengchen Thank you for solving my problem, but I still have a question, what does tcp2PFlushCount() mean?

**Comment by weikengchen** [comment]
Guess you will not need it. The number of the calls to `tcp2PFlushProfiled()`. Not useful for benchmarks.

A side note: Obliv-C is more likely an academic project so cannot hope for perfect documentation. 

- If you feel one function is confusing, try search in Github in "This repository". The code quality is okay, and Obliv-C is not a too complicated project.

- If you need example programs, some projects listed in this page (http://oblivc.org/) used Obliv-C, and many of them are open-sourced. That is how I start to learn how to use. 

Hope that would be useful :)

**Comment by samee** [comment]
> Obliv-C is more likely an academic project so cannot hope for perfect documentation.

One can always try to be better than the other academic projects 🙂 I haven't been responding here since I'm glad others area already doing a great job helping each other, so thanks everyone for that. In addition to the ways of getting help described above, just posting here with a question like you did is fine too. That way the next person with the same problem can find the solution. 

If we find ourselves repeatedly answering the same questions, we will probably address that in the tutorial, or some new FAQ page.

**Comment by zxf8876983** [comment]
@weikengchen Thank you for your suggestion, this is very helpful to me.

**Comment by evansuva** [comment]
Thanks, @samee @weikengchen @zxf8876983. The main documentation (which we aim to keep up to date and useful) for oblivc is in a different repository - probably should be moved into this one.
https://github.com/uvasrg/oblivc-web/blob/master/content/documentation.md
is used to generate http://oblivc.org/documentation/. (I believe the /web/ subdirectory in this https://github.com/samee/obliv-c/tree/obliv-c/web repository is obsolete and should probably be removed to avoid confusion.)

If you have suggestions/corrections to improve the documentation (which doesn't include any of the performance functions now but should), please submit a PR for https://github.com/uvasrg/oblivc-web/blob/master/content/documentation.md. 

Thanks!
