### ISSUE TITLE
on revealObliv##tname##Array

### ISSUE THREAD

**Issue by weikengchen** [samee/obliv-c#66]
Maybe batching is useful in revealing bits.

Consider the following application:
- Alice and Bob compute a 12345-bit-output function.
- They both receive all the outputs.

To return the result, a common solution is:
```
for(int i = 0; i < 12345; i++){
        revealOblivBool(&output_plaintex[i], output_obliv[i], 0);
}
```

A more elegant solution is:
```
revealOblivBoolArray(output_plaintext, output_obliv, 12345, 0);
```
which, however, as expanded in `obliv_bits.c`, is equivalent to the one above.

However, there is an issue on "network rounds".
- When we run ``revealOblivBool(Array)``  with ``party=0`` for one time, there is a roundtrip.

It is reasonable because each invocation to ``revealOblivBool`` may have ``side-effect``. As the revealed value is plaintext, the non-obliv program may decide the next step based on the just revealed value.

But, if a user just wants to reveal a lot of oblivious bools, and ends this 2PC, the current programming framework does not provide a way to reduce the unnecessary rounds.

When ``party=0``, each server sends one bit, receives one bit, and sends the next bit, and receives the next bit... We can take a look at the underlying `yaoGenrRevealOblivBits` function:
```
bool yaoGenrRevealOblivBits(ProtocolDesc* pd,
    widest_t* dest,const OblivBit* o,size_t n,int party)
{
  size_t i,bc=(n+7)/8;
  widest_t rv=0, flipflags=0;
  YaoProtocolDesc *ypd = pd->extra;
  for(i=0;i<n;++i) if(o[i].unknown)
    flipflags |= ((yaoKeyLsb(o[i].yao.w) != o[i].yao.inverted)?1LL<<i:0);
  // Assuming little endian
  if(party != 1) osend(pd,2,&flipflags,bc);
  if(party != 2) { orecv(pd,2,&rv,bc); rv^=flipflags; }
  for(i=0;i<n;++i) if(!o[i].unknown && o[i].knownValue)
    rv |= (1LL<<i);
  ypd->ocount+=n;
  if(party!=2) { *dest=rv; return true; }
  else return false;
}
```
This results in 12345 rounds.

A better solution is to somehow ``batch``. If a series of `revealOblivBool` are independent, they can be batched into one large osend/orecv.

**Comment by weikengchen** [comment]
Note that if we have 100Mb to be revealed to both parties. Each running one ``osend`` for 100Mb and then each running one ``orecv`` 100Mb is not a final solution.

Sending too much will cause EAGAIN. Both parties will be stuck in ``osend``. 

It looks like:
```
revealOblivBoolArray(output_plaintext, output_obliv, 12345, 0);
```

may not be better than:
```
revealOblivBoolArray(output_plaintext, output_obliv, 12345, 1);
revealOblivBoolArray(output_plaintext, output_obliv, 12345, 2);
```

**Comment by samee** [comment]
For reducing round-trips, I'd be fine replacing the current version of `revealOblivBoolArray` with something similar to `revealObliv##tname##Array`. Feel free to send me the change. It's all in `obliv_bits.c`

**Comment by weikengchen** [comment]
Good. I plan to PR this in about two weeks.
