### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by freelyyu** [samee/obliv-c#69]
I follow the instructions to install，during the process，it occurs a warning：the environment is not in sync with the current switch. You should run :eval 'opam config env'. I have tried to run it.But ,it keep warning.

**Comment by weikengchen** [comment]
seems like a history issue when opam runs on MacOS. Are you running on MacOS?

I found some posts, not sure whether they are helpful:
https://github.com/ocaml/opam/issues/2584
https://github.com/ocaml/opam/issues/2159

By the way, my experience... use Linux!

**Comment by freelyyu** [comment]
I run on linux. I am going to see the answer.

**Comment by freelyyu** [comment]
according to the last instruction，I should “Git-clone this repository, and compile:” ，could you tell me how to do. Thanks.

**Comment by weikengchen** [comment]
The README nearby I think gives the instruction that you need to run.

For Git-clone, I think it falls beyond the scope of this repo and is a more general question.
I would refer you to some GitHub learning lab: https://try.github.io/

**Comment by freelyyu** [comment]
OK， thank you

**Comment by freelyyu** [comment]
I am a preliminary learner,but I want to know the repository refers what . I am  ashamed to ask you  for this question.

**Comment by weikengchen** [comment]
Oh, it means https://github.com/samee/obliv-c

this one itself.

**Comment by freelyyu** [comment]
OK,thank you very much.

**Comment by freelyyu** [comment]
hello,I am sorry that  have another problem to trouble you,when I run the instruction:"./configure && make",  the terminal shows "make[1]  leaving the directory ......  ". I want to know whether it is  installed successfully or not.Thanks a lot
