### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by freelyyu** [samee/obliv-c#72]
I  am sorry to trouble you again.I am test the project--Secure Stable matching at scale which is developed on obliv-c.
![qq 20181103100236](https://user-images.githubusercontent.com/39991677/47947016-9e892a80-df4f-11e8-96a7-3bed6c7e5999.png)

I have install the obliv-c successfully. then,I follow the installing of the  Secure Stable matching at scale. when I step into step three.there occurs a probelm as below.I have export the path.but it still fails.
![qq 20181103100259](https://user-images.githubusercontent.com/39991677/47947025-afd23700-df4f-11e8-9142-61f6ecd7982b.png)

**Comment by weikengchen** [comment]
did you do step 3 by setting the OBLIVC_PATH?

By the way, I would recommend you to change the language of Ubuntu from Chinese to English -- crucial for doing research and coding. The Chinese name on the path could lead to unexpected consequences.

**Comment by weikengchen** [comment]
By the way, this will be a question for Secure Stable Matching, not for this repo.

**Comment by freelyyu** [comment]
yes, I set the path again and solved the problem. I will follow your advice. 
 I am sorry to take up your time, you are nice.thank you very much. I have tried to ask help for  Secure Stable Matching,but I did not receive his letter. 
 I want to ask for a new question. I have surf the internet to find how to make .oc but have no answers so far.

![qq 20181103110245](https://user-images.githubusercontent.com/39991677/47947535-2fb0cf00-df59-11e8-8f2a-0c11c1f7427d.png)

**Comment by weikengchen** [comment]
So to compile in Secure Stable Matching, all you need to do is to run `make` on the first directory with `Makefile`.

When you run that, there should be a directory named `build`. 

In its subdirectory `build/tests`, there will be a bunch of binary programs that you can run.

**Comment by freelyyu** [comment]
I make and  find  the executable programs  in  bulid/test.thank you
