### ISSUE TITLE
some problem about running

### ISSUE THREAD

**Issue by freelyyu** [samee/obliv-c#73]
Hello，I met some problems that is not associated  with obliv-c  but  secure-stable-matching  whose author does not  answer me. I  am  so sorry to trouble you again, I want to run the  test_match on a laptop,but I do not know it needs  what parameter. I have ask many of my friends but none knows the answer.I am sorry to trouble you again.  test_omatch  and the test.omatch.c is as below 
![qq 20181103145848](https://user-images.githubusercontent.com/39991677/47949153-0011bf00-df79-11e8-92e1-92f385edfaa8.png)

![qq 20181103150132](https://user-images.githubusercontent.com/39991677/47949196-b7a6d100-df79-11e8-952c-fa27728f70b2.png)

![qq 20181103150139](https://user-images.githubusercontent.com/39991677/47949204-c8574700-df79-11e8-90e4-8d65c67032a7.png)

**Comment by weikengchen** [comment]
Since this issue is now fully independent of obliv-c, I will not provide an answer.

**Comment by freelyyu** [comment]
OK thank you very much
