### ISSUE TITLE
Can the socket keeps alive?

### ISSUE THREAD

**Issue by imTyrant** [samee/obliv-c#80]
I used `obliv-c` to write an application which needs frequently comparison between two party. Creating a new socket during comparison is very inefficient.  So how could I open a socket to support a longer-term connection?

**Comment by samee** [comment]
If you manage your own sockets using POSIX sockets, you can use [`protocolUseTcp2PKeepAlive`](https://github.com/samee/obliv-c/issues/80). If you are unfamiliar with POSIX sockets you can either (a) look up any tutorial on the topic on the web, or (b) get an idea of how to use it by checking the implementation of the usual [`protocolAcceptTcp2P`](https://github.com/samee/obliv-c/blob/obliv-c/src/ext/oblivc/obliv_bits.c#L284) and [`protocolConnectTcp2P`](https://github.com/samee/obliv-c/blob/obliv-c/src/ext/oblivc/obliv_bits.c#L248) implementations (you might need to write your own keepAlive versions of these).
