### ISSUE TITLE
TCP read error: : Success

### ISSUE THREAD

**Issue by bonliu** [samee/obliv-c#83]
I used load_data() from the linreg example to load 2 files, and perform matrix multiplication. So far I think my program is loading the files correctly. But when I try to add 2 numbers, and reveal it, I will get this error: "TCP read error: : Success" and Segmentation fault at the end.

here is the part of my code that I think caused the problem:
![image](https://user-images.githubusercontent.com/31838335/51774668-2307c700-20c1-11e9-97c3-754197c95bb9.png)

Can anyone please tell me what I did wrong?

**Comment by evansuva** [comment]
The line `obliv float z = ox[1023] + oy[1023]` seems problematic, and could well lead to a segfault if the value of `io->n` is too low. I'm not sure what you are trying to do with that line, but shouldn't be using an index value like this. Maybe you want to use `io->n - 1`?

**Comment by bonliu** [comment]
I am trying to load data from 2 txt files. Each file contains 1024 data points. The ultimate goal is to perform matrix multiplication of the data I obtains from the file. But since I keep getting segfault, so I decided to do something simple, namely, adding the last elements from the 2 array. That is where the 1023 come from. I think I might figure out what the problem is. But could you be more elaborate on "shouldn't be using an index value like this" ? Is there a better way to access values in obliv array?

**Comment by evansuva** [comment]
Its okay to be accessing the array elements like this - you've declared `ox` as an array of `obliv float` so can access the individual array elements just like you would a regular C array.

**Comment by samee** [comment]
Another common issue: try using `calloc` instead of `malloc` for `ox` and `oy`. It shouldn't matter in this particular case if `toObliv` is just calling `feedOblivFloat`, but there are other cases where it does matter.

**Comment by weikengchen** [comment]
Yes. `calloc` will create a zeroized structure. Even if you don't feed anything to it, it can still be a valid pair of garbled labels.

**Comment by bonliu** [comment]
Thank you guys very much. I fixed my code. The problem was I used io->n before I assigned the value to it (which is done in load_data).

One more question: does obliv-c support 2D array? 
For example:
```C
obliv float *values = calloc(1024, sizeof(obliv float));
obliv float **rows = malloc(32*sizeof(obliv float**);
for (int i = 0; i < io->n; ++i) {
    rows[i] = &values[i*32];
}
```

**Comment by samee** [comment]
That should work. Except for this line:
```C
obliv float **rows = malloc(32*sizeof(obliv float*));
```
Probably won't matter, but you have an extra asterisk in that `malloc` parameter.

**Comment by bonliu** [comment]
Oops. That is a typo. I will try again. Thank you for your help!
