### ISSUE TITLE
Inconsistent results?

### ISSUE THREAD

**Issue by bonliu** [samee/obliv-c#84]
I am trying to write a obliv-c program which computes matrix multiplication. So far I am able to load 2 matrixes from 2 local files. However I am having some trouble computing the result. Here is my code:

```C
obliv float dotProd(obliv float *oa, int s1, int e1, obliv float *ob, int s2)
{
  obliv float dotProd = 0;
  int j = s2;
  int step = e1 - s1 + 1;
  for (int i = s1; i <= e1; i++)
  {
    dotProd += oa[i] * ob[j];
    j += step;
  }

  return dotProd;
}

void matrixMultiply(protocolIO *io, obliv float *m1, int r1, int c1, obliv float *m2, int c2, obliv float *res)
{
  int i = 0, j = 0, k = 0;
  int n = (r1 - 1) * c1;
  while (i <= n)
  {
    if (j == c2)
    {
      i += c1;
      j = 0;
    }
    res[k] = dotProd(m1, i, i + c1 - 1, m2, j);
    // revealOblivFloat(&io->t, res[k], 0);
    // printf("%d: %f\n", k, io->t);
    printf("CALCULATING[%d]\n", k);

    j++;
    k++;
  }
}

void myFun(void *args) {
  // load data....
  protocolIO *io = (protocolIO *)args;

  float *x = malloc(sizeof(float) * ALLOC);
  float *y = malloc(sizeof(float) * ALLOC);

  load_data(io, &x, &y, ocCurrentParty());
  obliv float *m1 = malloc(sizeof(obliv float) * 8*32);
  obliv float *m2 = malloc(sizeof(obliv float) * io->n);

  toObliv(m1, x, 1, 8*32);
  toObliv(m2, y, 2, io->n);

  obliv float *res = calloc(8*32, sizeof(obliv float));
  matrixMultiply(io, m1, 8, 32, m2, 32, res);

  for (i = 0; i < 8*32; ++i) {
    revealOblivFloat(&io->t, res[I], 0);
    printf("%d\t%f\n", i, io->t);
  }
  
}
````

The program is not able to print out the correct result when I do
```C
for (i = 0; i < 8*32; ++i) {
    revealOblivFloat(&io->t, res[I], 0);
    printf("%d\t%f\n", i, io->t);
  }
```
inside myFun() which is the function calls matrixMultiply().
However it shows the program computes the correct result inside matrixMultiply() when I added these 2 lines:
```C
revealOblivFloat(&io->t, res[k], 0);
printf("%d: %f\n", k, io->t);
```
Am I using the wrong function that causes the error?

**Comment by samee** [comment]
Why is `I` capitalized in `res[I]`?
Nothing really stands out in your code, but it's very hard for me to reason about indices the way it's written. E.g. I can't tell if there is any index out of bound error. Try rerunning the exact same code without any `obliv`, and see if it still gives you the right result. If so, then try to minimize the example into something small so I can understand what's going on.

Also, you can try to rewrite `matrixMultiply` into something easier to understand, e.g.

```C
// <First, zero-init everything>
for(i=0;i<r1;++i) for(j=0;j<c1;++j) for(k=0;k<c2;++k) res[i][k]+=m1[i][j]*m2[j][k];
```

**Comment by bonliu** [comment]
The capitalized I in res[I] is a typo when I formatted the code in markdown. I don't have that in my actual program.

I am sorry for the mass. But I couldn't get the 2d obliv float array to work, so I treat the matrix as 1d array. The main problem is 
```C
res[k] = dotProd(m1, i, i + c1 - 1, m2, j);
```
 is computed correctly inside matrixMultiply(), but after matrixMultiply() finished, when I access res  again in myFun(), it gives me random value and segmentation fault.

**Comment by bonliu** [comment]
I looked into the documentation and figured out the problem is that I have to declare my matrices as global variables instead of local.
