### ISSUE TITLE
obliv float not working with constants

### ISSUE THREAD

**Issue by mahmoudnabil** [samee/obliv-c#85]
Hi,
I tried the following code and it seems that obliv float data type has some issue with constant float assignment
```obliv float s = 1.1;```
```revealOblivFloat(&io->result,s,0);```

I am getting result = 1.0000

and if the contant float between 0 and 1 the result is always 0. any suggestions?

**Comment by samee** [comment]
Sorry about that. Can you try `1.1f` instead?

**Comment by mahmoudnabil** [comment]
The same issue if I tried `1.1f`, and if this value goes into the computations the fraction part is truncated.
I also noticed that this test case is missing here https://github.com/samee/obliv-c/blob/obliv-c/test/oblivc/testFloat/testFloatOps.oc

**Comment by samee** [comment]
Thanks for trying. I'll try to reproduce this on my end, running into some technical trouble on my end. Try to work around for now using s=11; s/=10; But this needs a proper solution.

**Comment by mahmoudnabil** [comment]
I did a similar work around.
Thank you for your fast replay and for this great work.
