### ISSUE TITLE
failed to run:/obliv-c/test/oblivc/psi

### ISSUE THREAD

**Issue by a870988925** [samee/obliv-c#93]
Hellow,
I wonder to know how to run psi?
There is no readme.txt `in /obliv-c/test/oblivc/psi.` 
And when I input the `./a.out`, it says Segmentation fault (core dumped).
like this
![IMG_20191109_103014](https://user-images.githubusercontent.com/49442227/68521530-fd108380-02dc-11ea-8d14-a2ede385cf54.jpg)

**Comment by samee** [comment]
You're right, looks like it was broken, sorry about that! I just pushed out 0fa103f2. See if it works now. A simple `make` in the `test/oblivc/psi` folder should do it now. The usage details is in `psi.c` (see commit link).

**Comment by a870988925** [comment]
I tried your method, but it is still the false: `segmentation fault`. As shown below, the terminal occurs warning `is cast to pointer from integer of different size size`.Is it the problem of this warning?

![2CD5DBBD86B245F9FEFED12D4AC3A111](https://user-images.githubusercontent.com/49442227/68572010-4f010700-049f-11ea-8fd6-3586d9e35ed2.jpg)

**Comment by samee** [comment]
Your screenshot still shows old code, from before the patch. Did you actually update your git repository? Try a `git pull` before your `make`.

**Comment by freelyyu** [comment]
you are right,Thank you.

**Comment by a870988925** [comment]
Thank you, Moreover, I found that these examples in `oblivc` are all 2PC , I  want to expand it to 3PC, then what should I do? For example,  how to modify the statement `setCurrentParty(&pd, argv[1][0]=='1'?1:2)` in million.

**Comment by samee** [comment]
Unfortunately that won't be easy. It requires plugging in a new protocol, and I'm not sure if we have one for millionaires. Some people have indeed extended Obliv-C for special applications, with special security models, e.g. https://github.com/schoppmp/linreg-mpc is a good one for linear regression.

If you want to write a new multiparty protocol for Obliv-C, you are certainly welcome to try.

**Comment by zhangyingjie7** [comment]
Hi, 

I meet a different when I try psi, that is “TCP connect failed” , as follow 

```
zyj@dinglab-poweredge-r740:~/obliv-c/test/oblivc/psi$ ./a.out -- 1234 & 
[1] 47907
zyj@dinglab-poweredge-r740:~/obliv-c/test/oblivc/psi$ TCP connect failed
./a.out localhost 1234
TCP connect failed
[1]+  exit 1                ./a.out -- 1234
zyj@dinglab-poweredge-r740:~/obliv-c/test/oblivc/psi$ 
```
