### ISSUE TITLE
Assertion `ocRandomBytes(pd,gen,ypd->yaoFixedKey,klen,3-pd->thisParty)' failed

### ISSUE THREAD

**Issue by bunnyxt** [samee/obliv-c#95]
Hello, there! I made a simple program using obliv-c and use ```cycle './a.out <party-1> <param-1> | ./a.out <party-2> <param-2>'``` to run it. However, I got the following error:

```
src/ext/oblivc/obliv_bits.c:1041: setupYaoFixedKeyCipher: Assertion `ocRandomBytes(pd,gen,ypd->yaoFixedKey,klen,3-pd->thisParty)' failed
```

I wanna know how this error triggered and possible solutions.

**Comment by samee** [comment]
Hi, thanks for the bug report. Unfortunately that's a fairly unusual error, so the only way I can help is if you can produce some minimal program that has that problem. Another way to approach this is to start from something that works. Does the example in test/oblivc/million work for you? Maybe you can then start making small modifications to it and see when exactly it breaks.

**Comment by bunnyxt** [comment]
> Hi, thanks for the bug report. Unfortunately that's a fairly unusual error, so the only way I can help is if you can produce some minimal program that has that problem. Another way to approach this is to start from something that works. Does the example in test/oblivc/million work for you? Maybe you can then start making small modifications to it and see when exactly it breaks.

@samee Hi! I solved this problem by removing printf("xxx") sentences in if(xx){xxx} block! Thank you a lot!
