### ISSUE TITLE
Extending source code to change gate representations of base circuits

### ISSUE THREAD

**Issue by rehanvipin** [samee/obliv-c#96]
Hi there!  
I'm working with an undergraduate research team who's using your library as one of the base for our project. Our research involves changing the basic circuits in yao's garbled circuit, to observe the changes in runtime and communication bandwidth. This would require us to change the circuits for full adder and multiplier and such.
I went through the source code and this seems to be the file defining addition:
https://github.com/samee/obliv-c/blob/obliv-c/src/ext/oblivc/obliv_float_add.c
How would we go about modifying this? Was this file generated by another program? How would go about modifying this file to make a different adder/multiplier?
Thank you.

**Comment by evansuva** [comment]
Darion Cassel (https://darioncassel.me/) did that work. I'm not sure if he'll see messages here, but you might try contacting him directly (you'll find his email on the website linked).

**Comment by rehanvipin** [comment]
Thank you, I'll contact him.

**Comment by samee** [comment]
Hi Rehan,

Yes definitely contact Darion if you want help with floating point circuits. But if you want the integer circuits, the definitions are in a different file. They are declared in https://github.com/samee/obliv-c/blob/obliv-c/src/ext/oblivc/obliv_bits.h#L85, and defined in obliv_bits.c, e.g. https://github.com/samee/obliv-c/blob/obliv-c/src/ext/oblivc/obliv_bits.c#L1640.

**Comment by rehanvipin** [comment]
I went through the code in those two files and those functions are exactly what we were looking for.
I have mailed Darion about the floating point circuits.
Thank you for the response :)

**Comment by darioncassel** [comment]
Hi all,

The floating point circuits are created with this Python script: https://github.com/samee/obliv-c/blob/obliv-c/SCDtoObliv/SCDtoObliv.py. There are instructions at the top of the script.

The gist of it is that you will need to get a circuit in the simple circuit description (SCD) format, which is produced by the TinyGarble toolchain: https://github.com/esonghori/TinyGarble, and then run `SCDtoObliv.py` with the path to the circuit as an argument, e.g.
```
python3 SCDtoObliv.py path/to/circuit.scd > circuit.c
```

The script prints the Obliv-C circuit to stdout so we redirect it to a file.

**Comment by rehanvipin** [comment]
That solved our problem, we look forward to using the library to the fullest.
Thank you all for your help and support.
