### ISSUE TITLE
building obliv-c on macOS 11.2.1

### ISSUE THREAD

**Issue by wrharris** [samee/obliv-c#97]
This isn't an issue, so much as it is a point of information (well, technically a non-critical "issue" with `README.md`, I suppose). I was recently able to build obliv-c on macOS 11.2.1: the README asked that I ping the devs with instructions on how to do so, so here the key changes that worked on my system. In general, it wasn't too big of a hassle: most of the pain came from the fact that recent versions of macOS seem to have put standard libraries and headers in a very non-standard location.

* The README gives instructions for building with macports; building with macports may still be entirely possible, but I use homebrew, so I tried to push through the installation with homebrew, and it wasn't too painful.
* When making oblivc, set `CC=/usr/local/bin/gcc-5`;
* Set `CPP=/usr/local/bin/cpp-5`;
* Export `CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/`;
* Export `LIBRARY_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib`.

Thanks for maintaining the tool in such good shape!

**Comment by samee** [comment]
Hi Bill, thanks for this! I'll be happy to link to it from the project `README.md`, or even just inline it there if it can be condensed to fit in that one bullet-point of Mac OS setup. Do you want to send me a pull request, or should I just link to this issue directly?

**Comment by wrharris** [comment]
No problem, just sent a pull request <https://github.com/samee/obliv-c/pull/98>.

**Comment by samee** [comment]
Thanks!
